### ISSUE TITLE
Compilation error on the bevy-0.14 branch

### ISSUE THREAD

**Issue by davi4046** [NoahShomette/bevy_eventwork_mod_websockets#6]
I wanted to toy around with this in bevy 0.14 but got a compilation error in BEMW.

Easiest way to replicate this error is to run examples/server. But you have to change the Eventwork dependency since the one referred to does not exist (as I think you are aware?).

Change dependency to this:

`bevy_eventwork = { git = "https://github.com/jamescarterbell/bevy_eventwork.git", rev = "dd0e82587cf79c3df8f840f55e8a65e127220af6" } # Eventwork 0.9
`

Error occurs on line 44 in `lib.rs`.

**Comment by NoahShomette** [comment]
Thanks for catching that! I pushed the right patch so everything should be working now. Just waiting on a crates release from bevy_eventwork to push this out

**Comment by davi4046** [comment]
Changing the dependency isn't the fix, it's just necessary to replicate the
error.

Try to run the server example. Does it compile?

**Comment by NoahShomette** [comment]
The server compiled fine for me on the branch. Do you have the exact error that it's throwing up?

**Comment by davi4046** [comment]
I will send it to you tomorrow.

It is really obscure. Something about the NetworkSettings struct not
implementing Resource (although it does derive Resource).

Maybe only on my side? I have no idea what I've done wrong though. I will
have another look at it tomorrow.

lør. 20. jul. 2024 22.54 skrev Noah ***@***.***>:

**Comment by NoahShomette** [comment]
If you can try the example again and see if it's fixed that would be great too. Normally the resource derive failing is caused by mismatched bevy versions and I ran into that before I swapped to the git tagged version number

**Comment by davi4046** [comment]
Okay, just tried one last time and I got it to work. Seems like it was caused by some outdated dependency but I really have no clue.

Thank you for the help, Noah!

**Comment by NoahShomette** [comment]
Glad it worked! Let me know if you run into any other issues
